### PR TITLE
Fixes for larger archives: read values as unsigned & fix block count calc

### PR DESCRIPTION
**Pull request by emoose**
Thanks for the tool, nothing else seemed to work on the game files, but I noticed this would error on some of the larger archives.

Had a look into it and think this should fix those, seems to fully extract core.psarc now, and files all look like they're extracted fine (at least a bunch of .png files I checked looked valid), tried a few of the other larger psarcs and they all extracted without error too.

I didn't test the import feature though (using orbis-psarc.exe seems to work fine for the game), but did update that with fixes for Temp1/Temp2 fields so should hopefully work on larger archives too.

I had to comment out the for loop at https://github.com/amrshaheen61/TLOU_PSARC_Tool/blob/a297812d095327b3d1e9f3dfd641c92caf8fd3da/TLOU%20PSARC%20Tool/Core/Psarc.cs#L136-L147 for certain files to extract though, seems those files had 1st block decompressed (so psarc.ArraySize[compressedBlockSizeIndex] == 0), but then following blocks were compressed.

The rest of the code seems setup to handle decompressed blocks fine but this loop was breaking it somehow, not really sure what the loop is doing, but with it commented out the files that had issues seem to work fine now.

The `Application.DoEvents` call just helps keep app from freezing as often, can still happen sometimes though, not really sure what better way to fix it is... maybe making a command-line version of this could get around it.

---

E: just did a test of extracting all the games .psarcs with this and recreating them with `orbis-psarc create -IFilesMap.txt -o[out-file-name] -N`, to create uncompressed psarc files out of them, and game seems to load fine with those extracted-and-repacked files 😸 

Sadly didn't notice much load time difference, seemed about the same to me. I wonder if running it uncompressed might help with traversal stutter at all though.
(I didn't really get much stutter on my system so can't really say if it helps though, maybe someone that has that issue could try the same thing here - you can find `orbis-psarc.exe` inside "Fake_PKG_Tools_v1.5.1` pack.

### CODE REVIEW

**Comment by emoose** [comment]
>Sadly didn't notice much load time difference, seemed about the same to me.

Ah might be wrong about that actually, uncompressed does seem to load a bit faster, maybe 10-20 seconds quicker for me.
Also tried playing game at 640x360 with framerate uncapped, to try and make sure I was cpu limited, with the vanilla game files I ran at about 120-130FPS, and had some hitches/stutters when moving around, but using decompressed copy it went to 140-150FPS, and didn't really notice any stutters at all 😱 

Still needs more testing on other machines, but looks promising.

**Comment by amrshaheen61** [comment]
@emoose 
https://zenhax.com/viewtopic.php?f=12&t=18213
```
No need to repack the psarc file, just rename the core.psarc to something else and extract all of the file inside core.psarc to main folder.
```
i think this will help

**Comment by amrshaheen61** [comment]
this for 
https://github.com/amrshaheen61/TLOU_PSARC_Tool/blob/a297812d095327b3d1e9f3dfd641c92caf8fd3da/TLOU%20PSARC%20Tool/Core/Psarc.cs#L136-L147 
get file size because
(size == uncompress size)
as you can see here the file is decompressed
image

**Comment by emoose** [comment]
Wow that method works really well, load times are almost non existent, loading into a save shows the spores for 10 seconds or so, loading bar finally appears on bottom right, then it disappears 1 second later and loads in :o

Seems there were 3 psarcs that would crash game if I tried unpacking & leaving them extracted tho, if I repack them with orbis-psarc it works fine so don't think it's issue with extract, guess game just doesnt allow them to be unpacked.

So it seems you can unpack every psarc except for these:
- bin.psarc
- common.psarc
- shaders.psarc

Wonder if editing the chunks.txt / paks.txt / etc files could help with them...

Maybe it could be worth adding some kind of Extract All function to the app, took a little while needing to pick them manually.

**Comment by amrshaheen61** [comment]
what?! bin.psarc is the only example i have 😐

**Comment by amrshaheen61** [comment]
@emoose 
try to unpack startup-dc-files.psarc insaide bin.psarc file also

**Comment by emoose** [comment]
Ahh looked in procmon and game tried reading the stuff inside bin.psarc from `The Last of Us Part I\build\pc\main\bin\dc1\` folder, the other psarcs all worked fine in \pc\main\, but looks like this needs a bin folder for it first.

Maybe the other two psarcs will work the same too, will give it a try now.

E: hm, shaders seem to be read from
`build\pc\main\bin\shaders\src\files.json`
So that also has to be in bin folder, odd, seems to work after I move it there.

Might have been wrong about common.psarc too, just copying contents into \build\pc\main\ seems to work

E2: couldn't find where to extract `build\pc\main\speech1\english.psarc` unfortunately, didn't see anything in procmon about it, seems game does try reading from speech0 folder but copying stuff there didn't really do anything, too bad, at least using uncompressed psarc works fine for that.

**Comment by amrshaheen61** [comment]
@emoose 
Ok good 👍🏻
I think it will work on my PC if I do that, have to give it a try

**Pull request merged**
